version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kushki_analyzer_backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - CORS_ORIGINS=*  # Allow frontend to access the backend
    restart: unless-stopped
    networks:
      - analyzer_net

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: kushki_analyzer_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - analyzer_net

networks:
  analyzer_net:
    driver: bridge
